# Generated by Django 3.0.3 on 2020-12-12 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custum_id1',
            name='custum_id1',
            field=models.BigAutoField(default=1000, editable=False, primary_key=True, serialize=False),
        ),
    ]
