# Generated by Django 3.1.2 on 2020-10-31 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('standard', models.IntegerField()),
                ('rollNo', models.IntegerField()),
                ('mobNo', models.CharField(max_length=10)),
            ],
        ),
    ]
