# Generated by Django 3.1.4 on 2021-01-22 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Myupload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images')),
                ('action', models.CharField(choices=[('NO_FILTER', 'no_filter'), ('COLORIZED', 'colorized'), ('GRAYSCALE', 'grayscale'), ('BINARY', 'binary'), ('INVERT', 'invert'), ('BLURED', 'blured')], max_length=100)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
